import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
    title: "IFC-CAD App",
    description: "Generated by Next.js",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <head>
                <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=0" />
            </head>
            <body className="antialiased w-screen h-screen overflow-hidden">
                {children}
            </body>
        </html>
    );
}
